"""initial

Revision ID: 63649da8b2e0
Revises: 
Create Date: 2026-03-31 20:58:05.324719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63649da8b2e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Identificador unico del usuario'),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nombre de usuario (unico)'),
    sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True, comment='Edad del usuario'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Correo electronico (unico)'),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Contrasena hasheada'),
    sa.Column('rol', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=True, comment='Rol del usuario (default: user)'),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nombre', name=op.f('usuarios_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Tabla de usuarios del sistema'
    )
    op.create_index(op.f('idx_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
