"""agrega dni

Revision ID: 85a33f599765
Revises: 63649da8b2e0
Create Date: 2026-04-03 22:17:56.436239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a33f599765'
down_revision: Union[str, Sequence[str], None] = '63649da8b2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('dni', sa.String(), nullable=True))
    op.alter_column('usuarios', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador unico del usuario',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Nombre de usuario (unico)')
    op.alter_column('usuarios', 'edad',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Edad del usuario',
               existing_nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Correo electronico (unico)')
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Contrasena hasheada')
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Rol del usuario (default: user)',
               existing_nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_index(op.f('idx_usuarios_id'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.drop_table_comment(
        'usuarios',
        existing_comment='Tabla de usuarios del sistema',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'usuarios',
        'Tabla de usuarios del sistema',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.create_index(op.f('idx_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=50),
               comment='Rol del usuario (default: user)',
               existing_nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Contrasena hasheada')
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Correo electronico (unico)')
    op.alter_column('usuarios', 'edad',
               existing_type=sa.INTEGER(),
               comment='Edad del usuario',
               existing_nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Nombre de usuario (unico)')
    op.alter_column('usuarios', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador unico del usuario',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('usuarios', 'dni')
    # ### end Alembic commands ###
